### PR TITLE
Fixed: Example LXC list code not working

### PR DESCRIPTION
**Pull request by TalhaQuddoos**
If you try to run:
```php
$proxmox->nodes()->lxc()->get()
```
It returns an error: `Nodes` has no method `lxc()`.

The code that worked for me, is:
```php
$proxmox->nodes()->node("node_name")->lxc()->get()
```

If you see the same problem happening, please merge this PR.

### CODE REVIEW

**Review by MrKampf — COMMENTED** [review]
Correct, thanks.

**Comment by TalhaQuddoos** [comment]
@MrKampf there are two other things that I want to talk about. 
1. When trying to log in, i.e.
```php
$proxmox = new PVE("host", "user", "password", port, "pve", true);
```
I get the error: 
```Server error: 501 malformed JSON string, neither array, object, number, string or atom, at character offset 0```
I tried it on two PHP 8.1 computers, and the problem was same. Did a bit of fix that worked.
Can you confirm if you are getting the same error when you try to do so? If so, I can open a pull request with my little fix.

Second thing - I am unable to get  the RRD Data for a selected container. I don't see anywhere in the code where I can specify the ```timeframe``` parameter, which is required.
The is my code so far:
```php
$data = $node->lxc()->vmId($vmid)->rrddata()->get();
```

But it throws an error that `timeframe` parameter is required. Any thoughts?
P.S. When I make the same request with Postman, it works.

**Comment by TalhaQuddoos** [comment]
@MrKampf any comments?

**Comment by MrKampf** [comment]
Yeah the first issue is correct, i have the same problem. Send a pull request and i accept it.

For the second i add a bugfix.

Thanks for support!

**Comment by MrKampf** [comment]
Commit for rrdata is online

**Pull request merged**
